export const ACTION_TYPES = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_AVAILABLE_HOUSES: "SET_AVAILABLE_HOUSES",
  SET_PERSONAL_LISTINGS: "SET_PERSONAL_LISTINGS",
  SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
  SET_ERROR: "SET_ERROR",
  REGISTER: "REGISTER",
  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
};
